### ISSUE TITLE
Color & Compiler flags

### ISSUE THREAD

**Issue by iambudi** [inim-repl/INim#103]
This is not an issue, just a question.

1. How to pass flag --threads:on to compiler so inim can run thread code?
2. Does --showColor works on mac? I don't see any color difference in the terminal (ITerm and Terminal with bash and zsh)

Thank you.

**Comment by 0atman** [comment]
Hi @iambudi! I'm afraid I don't have a mac to test the color flag, @Tangdongle do you have a mac to test on?

**Comment by 0atman** [comment]
if you run `inim --help` you can see all the options to pass in, one of which is:

```
-d=, --flags=  strings  {}  Nim flags to pass to the compiler
```
Hope that helps!

**Comment by iambudi** [comment]
Hi @0atman i clone the repo and the color works nicely. Seems there was an issue when i installed using nimble.
For the flag I still don't get it. Can you please check if i write it wrong?
```bash
# inim --flags=threads:on
```
```zsh
👑 INim 0.5.0
Nim Compiler Version 1.2.6 [MacOSX: amd64] at /usr/local/bin/nim

nim> import threadpool
/usr/local/Cellar/nim/1.2.6/nim/lib/pure/concurrency/threadpool.nim(21, 10) Error: Threadpool requires --threads:on option.
```

**Comment by 0atman** [comment]
@Tangdongle did we add this in in https://github.com/inim-repl/INim/pull/51 ?

**Comment by iambudi** [comment]
@0atman following #51 and add the flags to compileCmd array, no longer error. Just wondering why it does not work as app.flags.
```
let compileCmd = [
      app.nim, "compile", "--run", "--verbosity=0", "--threads=on", app.flags,
      "--hints=off", "--path=./", bufferSource
  ].join(" ")
```

**Comment by 0atman** [comment]
How odd! We should fix that, it's very confusing. Thank you for reporting it, I'll leave this issue open to track this.

**Comment by iambudi** [comment]
In `proc main`, the following line is the problem. 

```nim
if flags.len > 0:
    app.flags = " -d:" & join(@flags, " -d:")
```

so passing flag `--threads=on` become `-d=--threads=on` which is invalid arg for compiler.
i guess `-d` and `--something` are two different flags so it should be treated differently.

I'm new to nim, so does not know how to code it effectively but come up with this
```nim
import sugar
# to use map from sugar

if flags.len > 0:
    # app.flags = " -d:" & join(@flags, " -d:")
    app.flags = flags.map(f => ( 
        block:
          if f.startsWith("--"): 
            return f
          return fmt"-d:{f}"  
      )
    ).join(" ")
```
Now this works.
```bash
# inim --flags=--threads=on
# inim -d=ssl --flags=--threads=on 
```

**Comment by Tangdongle** [comment]
Sorry I missed this. Yeah, definitely an issue, nice solution @iambudi ! Do you want to pop that code fix into a PR?

**Comment by Tangdongle** [comment]
I'd made a PR with the fix above and a test

**Comment by iambudi** [comment]
@Tangdongle Thank you for the fix.

**Comment by Tangdongle** [comment]
@0atman This can be closed with https://github.com/inim-repl/INim/pull/104

**Comment by 0atman** [comment]
Extremely nice!
