### ISSUE TITLE
Error: cannot open file: src/inimpkg/commands

### ISSUE THREAD

**Issue by juancarlospaco** [inim-repl/INim#109]
```console
$ inim --withTools

👑 INim 0.6.0
Nim Compiler Version 1.2.6 [Linux: amd64] at /home/juan/.nimble/bin/nim
nim> import strutils
/tmp/inim_1601743616.nim(6, 22) Error: cannot open file: src/inimpkg/commands

```

- `--withTools` is not working.

**Comment by Tangdongle** [comment]
It looks like the commands file is not being bundled in the binary. We read src/inimpkg/embedded.nim correctly as we do a staticRead (which should store that value of that file in the inim binary as we're storing it at compile time). Problem is we're not doing the same with with the commands library, we're just including it in embedded.nim (which it then can't find as we don't include the src dir with nimble releases)

**Comment by juancarlospaco** [comment]
Repro on `0.6.1`.

**Comment by Tangdongle** [comment]
@juancarlospaco Hey mate, a fix has been merged for this. If you run `nimble install "inim@#head", that should grab you the version with the change. 

If this resolves this problem for you, we can mark this issue as done :rocket:
