### ISSUE TITLE
Got error when installing inim

### ISSUE THREAD

**Issue by Freakwill** [inim-repl/INim#113]
Got the following error when installing inim. (in macOS, nim latest version installed by homebrew)

It seems to require C compiler. I use gcc also installed by homebrew.

> /Users/william/.cache/nim/inim_r/stdlib_io.nim.c:12:10: fatal error: 'stdio.h'
>       file not found
> #include <stdio.h>
>          ^~~~~~~~~
> /Users/william/.cache/nim/inim_r/stdlib_system.nim.c:12:10: fatal error:
>       'sys/mman.h' file not found
> #include <sys/mman.h>
>          ^~~~~~~~~~~~
> 1 error generated.
> Error: execution of an external compiler program 'clang -c  -w -ferror-limit=3 -O3   -I/usr/local/Cellar/nim/1.4.0/nim/lib -I'/private/var/folders/md/8kgtqqz12j94hbcvhqz0w7gw0000gp/T/nimble_21686/githubcom_inimreplINim_#head' -o /Users/william/.cache/nim/inim_r/stdlib_io.nim.c.o /Users/william/.cache/nim/inim_r/stdlib_io.nim.c' failed with exit code: 1
> 
> 
>        Tip: 74 messages have been suppressed, use --verbose to show them.
>      Error: Build failed for package: inim
>         ... Execution failed with exit code 256
>         ... Command: /usr/local/Cellar/nim/1.4.0/nim/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.6.1 --path:/Users/william/.nimble/pkgs/cligen-1.3.2 --path:/Users/william/.nimble/pkgs/noise-0.1.4 --hints:off -o:'/var/folders/md/8kgtqqz12j94hbcvhqz0w7gw0000gp/T/nimble_21686/githubcom_inimreplINim_#head/inim' '/var/folders/md/8kgtqqz12j94hbcvhqz0w7gw0000gp/T/nimble_21686/githubcom_inimreplINim_#head/inim.nim'
> 1 error generated.

**Comment by Tangdongle** [comment]
Hey mate! Do you have issues installing anything else from nimble? 

Been a while since I used OSX. Which version are you running? 

To figure out if it's using the correct version of gcc, can you run `find / -name gcc 2&>/dev/null` to see which gcc versions are installed and post that here? Can you also post the output of `which gcc`?

Also run `find / -name mman.h 2&>/dev/null` to see if you have the missing header installed somewhere. I'm thinking that it's perhaps using the wrong version of gcc.

**Comment by Freakwill** [comment]
Thank you for your reply

Following is the information, too much to read by myself.

[~] which gcc
/usr/local/bin/gcc
[~] gcc --version
gcc (Homebrew GCC 10.2.0) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[~] nim -v                                                            11:33:45
Nim Compiler Version 1.4.0 [MacOSX: amd64]
Compiled at 2020-11-08
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise
[~] find / -name mman.h 2&>/dev/null                                  11:33:54
/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/sys/mman.h
/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/mman.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/mman.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/mman.h
/System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/mman.h
/System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/mman.h
/System/Volumes/Data/Applications/MATLAB.app/polyspace/verifier/cxx/include/include-libc/sys/mman.h
/System/Volumes/Data/Applications/MATLAB.app/polyspace/verifier/cxx/include/include-libc/bits/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/sys/mman.h
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sys/mman.h
/Applications/MATLAB.app/polyspace/verifier/cxx/include/include-libc/sys/mman.h
/Applications/MATLAB.app/polyspace/verifier/cxx/include/include-libc/bits/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/sys/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/sys/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/sys/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/sys/mman.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sys/mman.h
[~] find / -name mman.h 2&>/dev/null

**Comment by 0atman** [comment]
Hi @Freakwill, I'd reccomend installing nim using https://github.com/dom96/choosenim#choosenim, which allows managing your nim versions and updating to the latest. Uninstall the brew version.

That way, you'll be using the same, latest version of nim we're all using, and this bug might go away :muscle: 

Let us know how you get on! And as @Tangdongle says, make sure you can install other nimble packages too :ok_hand:
