### ISSUE TITLE
ArchLinux/AUR package

### ISSUE THREAD

**Issue by ssiyad** [inim-repl/INim#127]
I just packaged INim for AUR. You can find it at https://aur.archlinux.org/packages/inim-git/
I'm fairly new to Nim and doesn't know much about it, or this tool. So if I missed anything, especially any compiler flags, feel free to raise a PR at https://github.com/ssiyad/pkgbuilds/blob/master/inim-git/PKGBUILD

Thanks for this wonderful tool btw!

**Comment by 0atman** [comment]
Thank you very much! Credit to @AndreiRegiani and @Tangdongle and all the contributors!
