### ISSUE TITLE
support `cd, ls, pwd` as in ipython

### ISSUE THREAD

**Issue by timotheecour** [inim-repl/INim#21]
ipython supports `cd, ls, pwd`
these are very useful and commonly used.

2 ways to do that:

* using magic commands (not regular procs) that would have to be recognized specially by inim interpretter
eg:
```
cd mydir # would call setCurrentDir(mydir)
ls # would call something like osproc.execCmd("ls")
ls -al # likewise, osproc.execCmd("ls -a")
```

* using normal procs that would not have to be treated specially by inim interpretter
eg:
```nim
cd "mydir"
ls() #instead of ls
pwd() instead of pwd
call "ls -a" #  would call something like osproc.execCmd("ls -a")
```

I prefer the less magical option 2; `pwd()` is less nice than `pwd` as the only drawback but it's also much easer to implement and extend (simple import a module).

Either of these 2 options can be enabled via, say, `inim -with_tools`

**Comment by Tangdongle** [comment]
@0atman Can be closed by https://github.com/inim-repl/INim/pull/85
