### ISSUE TITLE
[feature] `foo | inim -s:-` to read foo from stdin as if it were a script

### ISSUE THREAD

**Issue by timotheecour** [inim-repl/INim#37]
```nim
cat foo.nim | inim # executes foo.nim line by line, using inim specific semantics (eg see https://github.com/AndreiRegiani/INim/issues/36)
inim -s:foo.nim # this doesn't use line-by-line interpretation

# proposal: this would have same semantics as `inim -s:foo.nim`
cat foo.nim | inim -s:-
```
compared to -s:foo.nim, it adds flexibility of unix pipes, or of avoiding user to write to an temporary file, etc.

## NOTE: nim itself actually understands `-` as meaning "stdin"
```nim
echo "echo 1" | nim c -o:app -r -
```
so there's nothing surprising there

**Comment by 0atman** [comment]
Interesting! What would this feature give the user, over piping to `nim c -o:app -r -`?

**Comment by Tangdongle** [comment]
@0atman This is fixed with https://github.com/inim-repl/INim/pull/100 . The `-s` argument logic was fixed to read from stdin if presented with `-` as an argument. Should run like `cat bug.nim | nim c -r -`
