### ISSUE TITLE
Edit command using external editor

### ISSUE THREAD

**Issue by drslump** [inim-repl/INim#41]
On shells it's usually available a way to edit the command on a external editor. For instance in Bash it's `<ctrl>+x e`, on Fish it's `<esc> e`. This launches the default text editor at the `$EDITOR` env var (usually vim or nano) to edit the current command prompt.

It's a very useful feature when you have to edit multiline snippets from history or just want to copy-paste something without the `...` prompt.

Great project!

**Comment by 0atman** [comment]
Really good idea, makes a lot of sense with multi-line, indented code.

**Comment by Tangdongle** [comment]
@0atman This can be closed with https://github.com/inim-repl/INim/pull/88
