### ISSUE TITLE
a "help" command would be useful

### ISSUE THREAD

**Issue by jabbalaci** [inim-repl/INim#48]
A "help" command in the REPL would be useful. When I tried INim, I could only guess how to quit. Ctrl+D didn't work (I just sent a PR about it), "help" wasn't available.

Update: I can do it in the form of a PR.

**Comment by bevo009** [comment]
Well, thanks for coding that jabbalaci, I will definitely use it once implemented. Seems Andrei has been absent from here, maybe ask on gitter?

**Comment by 0atman** [comment]
@AndreiRegiani has kindly let me maintain this repo - this issue is my personal number 1 feature.

As @jabbalaci says, we're trying to get ctrl+d to work, but due to the underlying library nim uses for input, it's quite difficult. Come and check out #56 for deets

**Comment by 0atman** [comment]
fixed all the things!
