### ISSUE TITLE
recent commit broke Nim CI

### ISSUE THREAD

**Issue by timotheecour** [inim-repl/INim#63]
/cc @0atman 
is there no CI in place that would've caught this?

https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/4285/logs/75

```
2020-04-14T09:38:46.2229348Z Hint: killring [Processing]
2020-04-14T09:38:46.2229583Z Hint: deques [Processing]
2020-04-14T09:38:46.2230813Z /home/vsts/work/1/s/pkgstemp/inim/src/inim.nim(366, 6) Hint: 'main' is declared but not used [XDeclaredButNotUsed]
2020-04-14T09:38:46.2231992Z /home/vsts/work/1/s/pkgstemp/inim/src/inim.nim(4, 69) Warning: imported and not used: 'streams' [UnusedImport]
2020-04-14T09:38:46.2232585Z /home/vsts/work/1/s/pkgstemp/inim/tests/test.nim(4, 8) Error: type mismatch: got <>
2020-04-14T09:38:46.2232952Z but expected one of: 
2020-04-14T09:38:46.2233299Z proc initApp(nim, srcFile: string; showHeader: bool; flags = "")
2020-04-14T09:38:46.2233567Z 
2020-04-14T09:38:46.2233917Z expression: initApp()
2020-04-14T09:38:46.2234545Z        Tip: 22 messages have been suppressed, use --verbose to show them.
2020-04-14T09:38:46.2234948Z      Error: Execution failed with exit code 1
2020-04-14T09:38:46.2236384Z         ... Command: "/home/vsts/work/1/s/bin/nim" c --noNimblePath -d:NimblePkgVersion=0.4.3 --path:"/home/vsts/.nimble/pkgs/cligen-0.9.43" --path:"/tmp/nimble_27096/githubcom_jangkonimnoise" "-r" "--path:."  "/home/vsts/work/1/s/pkgstemp/inim/tests/test"
2020-04-14T09:38:46.2237088Z 
2020-04-14T09:50:20.6926852Z [32mPASS: [36mhttps://github.com/narimiran/itertools C                    [34m ( 3.49 sec)[0m
```

can also repro via:
```
NIMBLE_DIR=$HOME/.nimble_fake14 nimble test

  Executing task test in /Users/timothee/git_clone/nim/temp/INim/inim.nimble
/Users/timothee/git_clone/nim/temp/INim/inim_95807.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedImport]
  Verifying dependencies for inim@0.4.4
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.43
      Info: Dependency on noise@any version already satisfied
  Verifying dependencies for noise@0.1.3
  Compiling /Users/timothee/git_clone/nim/temp/INim/tests/test (from package inim) using c backend
/Users/timothee/git_clone/nim/temp/INim/tests/test.nim(1, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/temp/INim/src/inim.nim(4, 69) Warning: imported and not used: 'streams' [UnusedImport]
  import os, osproc, strformat, strutils, terminal, times, strformat, streams
                                                                      ^
/Users/timothee/git_clone/nim/temp/INim/tests/test.nim(4, 8) Error: type mismatch: got <>
but expected one of:
proc initApp(nim, srcFile: string; showHeader: bool; flags = "")

expression: initApp()
  initApp()
         ^

```

**Comment by 0atman** [comment]
You're on the ball! Thank you for reporting this.

But... it works for me:

```
 λ~ nimble update
Downloading Official package list
    Success Package list downloaded.

 λ  ~ nimble install inim
Downloading https://github.com/inim-repl/INim using git
  Verifying dependencies for inim@0.4.4
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.43
      Info: Dependency on noise@any version already satisfied
  Verifying dependencies for noise@0.1.3
 Installing inim@0.4.4
   Building inim/inim using c backend
    Prompt: inim@0.4.4 already exists. Overwrite? [y/N]
    Answer: y
   Success: inim installed successfully.
```

I don't recognize what you're doing, as I'm new to Nim - how can I help?

**Comment by 0atman** [comment]
OH! the INim tests. right! I'm a professional :laughing: 

Fixing now. Great idea to get some CI, maybe a simple github action :ok_hand:

**Comment by 0atman** [comment]
do you know a good way of setting up CI?

**Comment by timotheecour** [comment]
setting up proper CI could take some time, but if you have a simple fix in the meantime (to un-break nim CI) that would be appreciated!
just make sure `nimble test` passes locally

as for a good way, i recommend azure pipelines (10 free parallel builds); pick your favorite starting point:
https://github.com/search?q=filename%3Aazure-pipelines.yml+nim

**Comment by 0atman** [comment]
@timotheecour I've commented the offending test, pending a fix. Tests now pass. 

What caught this error? Do you run a pipeline for every nimble package?

**Comment by 0atman** [comment]
Fixed in v0.4.5

**Comment by timotheecour** [comment]
> What caught this error? Do you run a pipeline for every nimble package?

Nim/testament/important_packages.nim, run by nim's CI for each PR

> Fixed in v0.4.5

confirm it works, thanks for the quick fix!
ya definitely a CI is needed; 

simplest i could find is https://github.com/loloicci/nimly/blob/429db84b4a4fed9ee6caaeb636634b20c66307c3/azure-pipelines.yml ; maybe try that?

**Comment by 0atman** [comment]
I'm scared to be the maintainer of an "important package" - time to get serious!

I'll set up strong CI. Cheers!

**Comment by 0atman** [comment]
@timotheecour do you have time to help me understand the OSError in my new CI? https://github.com/inim-repl/INim/runs/585421353

**Comment by 0atman** [comment]
I think I figured it out! `nim-noise`'s tests run with `-d:prompt_no_history`, so as to not create temp files. I'll try that in our tests.

**Comment by 0atman** [comment]
![Nim CI](https://github.com/inim-repl/INim/workflows/Nim%20CI/badge.svg)

**Comment by timotheecour** [comment]
> @timotheecour do you have time to help me understand

sorry, I just saw ur msg (US/CA time zone...)

> I think I figured it out

great! now that you've set up CI, I could also recommend merging through PR's instead of directly pushing to master; that's a good practice (eg you can see CI running and squash+merge each PR once CI is green; also better to get feedback etc)
