### ISSUE TITLE
InitApp test broken

### ISSUE THREAD

**Issue by 0atman** [inim-repl/INim#64]
Had to comment it out as I couldn't understand how to quickly fix it
https://github.com/inim-repl/INim/blob/78980a70b7204d9d4afc3f8e896931a493fd7be1/tests/test.nim#L5

**Comment by Yardanico** [comment]
It can be fixed by changing it to:
```nim
initApp("nim", "", true)
```

**Comment by 0atman** [comment]
So it can, thank you! Fixed in https://github.com/inim-repl/INim/commit/cbf49a14f13778583b911fd00a66919023e287e4
