### ISSUE TITLE
OSError if ~/.config doesn't exist

### ISSUE THREAD

**Issue by clive-g-brown** [inim-repl/INim#79]
👑 INim 0.4.7
Nim Compiler Version 1.2.0 [MacOSX: amd64] at /Users/xxxxx/.nimble/bin/nim
oserr.nim(94)            raiseOSError
Error: unhandled exception: No such file or directory
Additional info: "/Users/xxxxx/.config/inim" [OSError]

which I just fixed by making a .config/inim directory

**Comment by Tangdongle** [comment]
Hmmm, I assume your `.config` directory already existed when you ran it?

**Comment by 0atman** [comment]
is this because .config doesnt exist on osx?

**Comment by clive-g-brown** [comment]
yes if you create one - its fine.

**Comment by 0atman** [comment]
great, it should be a simple matter to catch that case, thanks for reporting! :ok_hand:
