### ISSUE TITLE
multi line paste only pastes 1st line

### ISSUE THREAD

**Issue by timotheecour** [inim-repl/INim#8]
eg:
```nim
echo 1
echo 2
echo 3
```

**Comment by AndreiRegiani** [comment]
Some info on the issue, INim uses the module `rdstdin` for input, which calls C lib `linenoise`.

https://github.com/nim-lang/Nim/blob/master/lib/impure/rdstdin.nim#L79
https://github.com/antirez/linenoise

**Comment by timotheecour** [comment]
we could use this: https://github.com/msteveb/linenoise/commit/08d3e5963297d275b5420b12e311381bee4d37f5
> Implement multiline and hints support

**Comment by Tangdongle** [comment]
@0atman This is fixed with the introduction of the Nim linenoise library, which allows for mult-iline pastes

**Comment by 0atman** [comment]
Nice cleanup!
