### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by jabbalaci** [inim-repl/INim#90]
Under Manjaro Linux, naive installation failed:

```
$ nimble install inim
Downloading https://github.com/inim-repl/INim using git
  Verifying dependencies for inim@0.5.0
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.17
      Info: Dependency on noise@any version already satisfied
  Verifying dependencies for noise@0.1.3
 Installing inim@0.5.0
   Building inim/inim using c backend
    Prompt: Build failed for 'inim@0.5.0', would you like to try installing 'inim@#head' (latest unstable)? [y/N]
    Answer:
```

However, I could install it this way:

```
$ nimble install cligen
$ nimble install inim
```

Please add `cligen` as a dependency.

**Comment by jabbalaci** [comment]
I just checked and `cligen` is indicated as a requirement. However, the installation failed. When I used `nimble install cligen`, it installed cligen v1.0.0 and inim installed correctly.

So I think this line in `inim.nimble` should be updated:

    requires "cligen >= 0.9.15"

to

    requires "cligen >= 1.0.0"

**Comment by Tangdongle** [comment]
Thanks for looking into that @jabbalaci , I've updated that in the nimble file now with the PR attached
