### ISSUE TITLE
how do you un-indent for the `else`?

### ISSUE THREAD

**Issue by unspam** [inim-repl/INim#93]
Maybe I'm missing something obvious here, but how does one unindent? I'm on MacOS Catalina trying to run inim 0.5.0 over iTerm2 (have also tried Terminal and Alacritty without success).

Backspace doesn't work at the start of the indented line, and it doesn't automatically try to match the `else` with the `if` etc. so I end up with erroneous code. I've tried the usual shortcuts to no avail.

**Comment by Tangdongle** [comment]
Yeah, looks like updating the actual prompt with the indent level is silly. I've submitted a PR for this

**Comment by Tangdongle** [comment]
@0atman This can be closed with https://github.com/inim-repl/INim/pull/98
